Add replicated supporrt for Azure, and add more retied in many places - v7.3

diff --git a/setup/wn/exa_cloud/aws/exa_cloud_upload b/setup/wn/exa_cloud/aws/exa_cloud_upload
--- a/setup/wn/exa_cloud/aws/exa_cloud_upload
+++ b/setup/wn/exa_cloud/aws/exa_cloud_upload
@@ -16,5 +16,26 @@ fi
 s3_path=`echo "${cloud_path}" | sed 's/http.*:/s3:/' | sed 's/..3.amazonaws.com//'`
 
 echo "INFO: Uploading to ${s3_path} (${cloud_path})"
-aws s3 cp --acl public-read --only-show-errors "$1" "${s3_path}"
+errstr=`aws s3 cp --acl public-read --only-show-errors "$1" "${s3_path}" 2>&1`
+rc=$?
+if [ $rc -ne 0 ]; then
+  sleep 1
+  echo "INFO: Retrying upload"
+  errstr=`aws s3 cp --acl public-read --only-show-errors "$1" "${s3_path}" 2>&1`
+  rc=$?
+fi
+if [ $rc -ne 0 ]; then
+  sleep 5
+  echo "INFO: Retrying upload"
+  errstr=`aws s3 cp --acl public-read --only-show-errors "$1" "${s3_path}" 2>&1`
+  rc=$?
+fi
+
+if [ ${rc} -ne 0 ]; then
+  echo "ERROR: Upload failed"
+  echo "ERROR: Upload failed" 1>&2
+  echo "$errstr" 1>&2
+  exit 1
+fi
+exit 0
 
diff --git a/setup/wn/exa_cloud/azure/exa_cloud_download_local_replicated b/setup/wn/exa_cloud/azure/exa_cloud_download_local_replicated
--- a/setup/wn/exa_cloud/azure/exa_cloud_download_local_replicated
+++ b/setup/wn/exa_cloud/azure/exa_cloud_download_local_replicated
@@ -1,19 +1,12 @@
 #!/bin/bash 
 
 #
-# Download a file from the local cloud storage
+# Download a file from the local cloud storage, assume it was replicated
 #
 
 if [ $# -ne 2 ]; then
   echo "ERROR: Missing arguments" 1>&2
-  echo "Usage: exa_cloud_download_local cloudpath localfile" 1>&2
-  exit 1
-fi
-
-# Use the upload mangle, which is always local
-cloud_path=`exa_cloud_mangle "$1"`
-if [ $? -ne 0 ]; then
-  echo "ERROR: Failed parsing cloudpath: ${cloud_path}" 1>&2
+  echo "Usage: exa_cloud_download_local_replicated cloudpath localfile" 1>&2
   exit 1
 fi
 
@@ -21,11 +14,20 @@ apath="$(realpath $2)"
 dpath="$(dirname $apath)"
 lpath="$(basename $apath)"
 
+
+cloud_path=`exa_cloud_replica_path RANDOM "$1"`
+if [ $? -ne 0 ]; then
+  echo "ERROR: Failed parsing cloudpath: ${cloud_path}" 1>&2
+  exit 1
+fi
+
 rm -f "${apath}"
 aria2c --max-tries=32 --retry-wait=1 -q -d "${dpath}" -o "${lpath}" "${cloud_path}"
 rc=$?
 if [ $rc -ne 0 ]; then
   # saw DNS problems before... try with less agressive setup
+  # also try a diffferent replica
+  cloud_path=`exa_cloud_replica_path RANDOM "$1"`
   rm -f "${apath}"
   aria2c --max-tries=32 --retry-wait=1 --async-dns=false -q -d "${dpath}" -o "${lpath}" "${cloud_path}"
   rc=$?
@@ -33,6 +35,8 @@ fi
 if [ $rc -ne 0 ]; then
   # ok, the storage may be quite overloaded... wait a tiny bit, and retry
   sleep 5
+  # also try a different replica
+  cloud_path=`exa_cloud_replica_path RANDOM "$1"`
   rm -f "${apath}"
   aria2c --max-tries=32 --retry-wait=1 --async-dns=false -q -d "${dpath}" -o "${lpath}" "${cloud_path}"
   rc=$?
diff --git a/setup/wn/exa_cloud/azure/exa_cloud_upload b/setup/wn/exa_cloud/azure/exa_cloud_upload
--- a/setup/wn/exa_cloud/azure/exa_cloud_upload
+++ b/setup/wn/exa_cloud/azure/exa_cloud_upload
@@ -18,7 +18,9 @@ if [ ${rc} -ne 0 ]; then
   errstr=`azcopy login --identity 2>&1`
   rc=$?
   if [ ${rc} -ne 0 ]; then
-    echo "$errstr"
+    echo "ERROR: Upload failed"
+    echo "ERROR: Upload failed" 1>&2
+    echo "$errstr"  1>&2
     exit 1
   fi
 fi 
@@ -29,12 +31,22 @@ errstr=`azcopy cp --no-guess-mime-type --log-level=ERROR "$1" "${cloud_path}"`
 rc=$?
 if [ ${rc} -ne 0 ]; then
   sleep 1
+  echo "INFO: Retrying upload"
   errstr=`azcopy cp --no-guess-mime-type --log-level=ERROR "$1" "${cloud_path}"`
   rc=$?
-  if [ ${rc} -ne 0 ]; then
-    echo "$errstr"
-    exit 1
-  fi
+fi
+if [ ${rc} -ne 0 ]; then
+  sleep 5
+  echo "INFO: Retrying upload"
+  errstr=`azcopy cp --no-guess-mime-type --log-level=ERROR "$1" "${cloud_path}"`
+  rc=$?
+fi
+
+if [ ${rc} -ne 0 ]; then
+  echo "ERROR: Upload failed"
+  echo "ERROR: Upload failed" 1>&2
+  echo "$errstr" 1>&2
+  exit 1
 fi
 exit 0
 
diff --git a/setup/wn/exa_cloud/exa_cloud_download b/setup/wn/exa_cloud/exa_cloud_download
--- a/setup/wn/exa_cloud/exa_cloud_download
+++ b/setup/wn/exa_cloud/exa_cloud_download
@@ -20,11 +20,28 @@ apath="$(realpath $2)"
 dpath="$(dirname $apath)"
 lpath="$(basename $apath)"
 
+rm -f "${apath}"
 aria2c --max-tries=32 --retry-wait=1 -q -d "${dpath}" -o "${lpath}" "${cloud_path}"
 rc=$?
 if [ $rc -ne 0 ]; then
+  # saw DNS problems before... try with less agressive setup
+  rm -f "${apath}"
+  aria2c --max-tries=32 --retry-wait=1 --async-dns=false -q -d "${dpath}" -o "${lpath}" "${cloud_path}"
+  rc=$?
+fi
+if [ $rc -ne 0 ]; then
+  # ok, the storage may be quite overloaded... wait a tiny bit, and retry
+  sleep 5
+  rm -f "${apath}"
+  aria2c --max-tries=32 --retry-wait=1 --async-dns=false -q -d "${dpath}" -o "${lpath}" "${cloud_path}"
+  rc=$?
+fi
+if [ $rc -ne 0 ]; then
+  # we have to give up, eventually
   echo "ERROR: Download of ${cloud_path} failed." 2>&1
+  echo "ERROR: Download of ${cloud_path} failed." 1>&2
 else
-  echo "INFO: Downloaded ${cloud_path} into ${apath}" 2>&1
+  echo "INFO: Downloaded ${cloud_path} into ${apath}" 
 fi
 exit $rc
+
